<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aitor Ameztegui (UdL)">
<meta name="dcterms.date" content="2024-08-22">

<title>Apuntes y ejercicios de geoestadística para forestales - 5&nbsp; Regresión lineal generalizada (GLM) en R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03_DatosEspaciales.html" rel="next">
<link href="./01_RegresionLineal.html" rel="prev">
<link href="./images/udl.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_RegresionLineal.html">UNIDAD 1: ANÁLISIS DE REGRESIÓN</a></li><li class="breadcrumb-item"><a href="./02_GLM.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regresión lineal generalizada (GLM) en R</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Apuntes y ejercicios de geoestadística para forestales</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/hadley/r4ds/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">UNIDAD 0: INTRODUCCION</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_Familiar_RStudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Familiarizándose con R y RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_Intro_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción a R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_RMarkdown_Quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introducción a Quarto y RMarkdown</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">UNIDAD 1: ANÁLISIS DE REGRESIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_RegresionLineal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresión lineal en R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_GLM.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regresión lineal generalizada (GLM) en R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">UNIDAD 2: GEOESTADÍSTICA Y ANÁLISIS ESPACIAL</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_DatosEspaciales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Trabajando con datos espaciales en R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_AutocorrelacionEspacial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Autocorrelación espacial en ArcGIS y R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_PatronPuntos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Análisis de patrón de puntos en R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_InterpolacionEspacial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpolación espacial en R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_RegresionEspacial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regresión espacial en R</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción-los-modelos-lineales-generalizados-glms" id="toc-introducción-los-modelos-lineales-generalizados-glms" class="nav-link active" data-scroll-target="#introducción-los-modelos-lineales-generalizados-glms"><span class="header-section-number">5.1</span> Introducción: los modelos lineales generalizados (GLMs)</a></li>
  <li><a href="#regresión-de-conteos-la-distribución-de-poisson" id="toc-regresión-de-conteos-la-distribución-de-poisson" class="nav-link" data-scroll-target="#regresión-de-conteos-la-distribución-de-poisson"><span class="header-section-number">5.2</span> Regresión de conteos: la distribución de Poisson</a>
  <ul class="collapse">
  <li><a href="#interpretando-los-resultados-de-un-glm-de-poisson" id="toc-interpretando-los-resultados-de-un-glm-de-poisson" class="nav-link" data-scroll-target="#interpretando-los-resultados-de-un-glm-de-poisson"><span class="header-section-number">5.2.1</span> Interpretando los resultados de un GLM de Poisson</a></li>
  <li><a href="#haciendo-predicciones-con-glms-de-poisson" id="toc-haciendo-predicciones-con-glms-de-poisson" class="nav-link" data-scroll-target="#haciendo-predicciones-con-glms-de-poisson"><span class="header-section-number">5.2.2</span> Haciendo predicciones con GLMs de Poisson</a></li>
  </ul></li>
  <li><a href="#regresión-de-eventos-binomiales-regresión-logística" id="toc-regresión-de-eventos-binomiales-regresión-logística" class="nav-link" data-scroll-target="#regresión-de-eventos-binomiales-regresión-logística"><span class="header-section-number">5.3</span> Regresión de eventos binomiales: regresión logística</a>
  <ul class="collapse">
  <li><a href="#interpretando-los-resultados-de-un-glm-logístico" id="toc-interpretando-los-resultados-de-un-glm-logístico" class="nav-link" data-scroll-target="#interpretando-los-resultados-de-un-glm-logístico"><span class="header-section-number">5.3.1</span> Interpretando los resultados de un GLM logístico</a></li>
  <li><a href="#haciendo-predicciones-con-glm-logístico" id="toc-haciendo-predicciones-con-glm-logístico" class="nav-link" data-scroll-target="#haciendo-predicciones-con-glm-logístico"><span class="header-section-number">5.3.2</span> Haciendo predicciones con GLM logístico</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">5.4</span> Conclusiones</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/hadley/r4ds/edit/main/02_GLM.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/hadley/r4ds/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regresión lineal generalizada (GLM) en R</span></h1>
<p class="subtitle lead">Geoestadística i Tècniques d’Observació Global (24/25)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aitor Ameztegui (UdL) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 22, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introducción-los-modelos-lineales-generalizados-glms" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introducción-los-modelos-lineales-generalizados-glms"><span class="header-section-number">5.1</span> Introducción: los modelos lineales generalizados (GLMs)</h2>
<p>Ya hemos visto en las clases teóricas que la regresión lineal generalizada (o modelos lineales generalizados, GLM) son una alternativa sólida a los casos en los que nuestra variable dependiente no sigue una distribución normal, y por tanto, los residuos de la regresión lineal no cumplirán los supuestos de la misma. Los GLM abordan estos problemas flexibilizando la distribución de la variable respuesta, y conectándola con un predictor lineal a través de una función de enlace (<em>link function</em>). Vamos a ver ahora ejemplos con algunas de las distribuciones más habituales - más allá de la normal:</p>
</section>
<section id="regresión-de-conteos-la-distribución-de-poisson" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="regresión-de-conteos-la-distribución-de-poisson"><span class="header-section-number">5.2</span> Regresión de conteos: la distribución de Poisson</h2>
<p>Uno de los casos más habituales en los que debemos usar los GLM es cuando nuestra variable dependiente son conteos. En este caso seguirán una distribución de Poisson, que se caracteriza como el número de veces que un determinado evento ocurrirá en un intervalo de tiempo. Si es un conteo de abundancia, por ejemplo, la variable dependiente será el número de plantas (eventos) en un muestreo. La distribución de Poisson tiene un sólo parámetro <span class="math inline">\(\lambda\)</span>, que es la media de eventos esperada. Así, si generamos una serie de 100 observacions con <span class="math inline">\(\lambda\)</span> = 5:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>poisson <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="dv">500</span>,<span class="dv">5</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(poisson, <span class="at">breaks =</span> <span class="dv">20</span>, <span class="at">main =</span> <span class="st">"Histograma de dist. Poisson de media 5"</span>, <span class="at">xlab =</span> <span class="st">"Número de eventos"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02_GLM_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>vemos que todos los valores son números enteros, ya que no puede haber, lógicamente, valores como <em>3,56 plantas</em>.</p>
<p>Para ajustar cualquier GLM usaremos la función <code>glm</code>, que viene cargada por defecto en R y que tiene tres argumentos principales:</p>
<ul>
<li><strong>Formula</strong>: la ecuación que define la variable dependiente y las independientes. Es igual que en la regresión lineal.</li>
<li><strong>data</strong>: el data frame que contiene las variables</li>
<li><strong>family</strong>: una descripción de la distribución que sigue el error y la función de enlace a usar. En el caso de conteos debe tomar el valor <code>"poisson"</code></li>
</ul>
<p>Vamos a ajustar una sencilla regresión Poisson usando datos de:</p>
<p>https://stats.idre.ucla.edu/stat/data/poisson_sim.csv</p>
<p>En este ejemplo, <code>num_awards</code> es el número de premios ganados por los alumnos de un instituto en un año, <code>math</code> es una variable continua que representa la nota obtenida por los estudiantes en el examen final de matemáticas, y <code>prog</code> es una variable categórica con tres niveles que indica el tipo de programa en el que están matriculados: 1 = “General”, 2 = “Academic” y 3 = “Vocational”.</p>
<p>Como siempre, carguemos los datos y echémosles un vistazo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>premios <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'https://stats.idre.ucla.edu/stat/data/poisson_sim.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(premios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   200 obs. of  4 variables:
 $ id        : int  45 108 15 67 153 51 164 133 2 53 ...
 $ num_awards: int  0 0 0 0 0 0 0 0 0 0 ...
 $ prog      : int  3 1 3 3 3 1 3 3 3 3 ...
 $ math      : int  41 41 44 42 40 42 46 40 33 46 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(premios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id num_awards prog math
1  45          0    3   41
2 108          0    1   41
3  15          0    3   44
4  67          0    3   42
5 153          0    3   40
6  51          0    1   42</code></pre>
</div>
</div>
<p>Ahora podemos ajustar un modelo de Poisson. Para ello:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mod.poisson <span class="ot">&lt;-</span> <span class="fu">glm</span>(num_awards <span class="sc">~</span> math <span class="sc">+</span> prog,  <span class="at">data =</span> premios, <span class="at">family =</span> <span class="st">"poisson"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = num_awards ~ math + prog, family = "poisson", data = premios)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -5.578057   0.676823  -8.242   &lt;2e-16 ***
math         0.086121   0.009586   8.984   &lt;2e-16 ***
prog         0.123273   0.163261   0.755     0.45    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 287.67  on 199  degrees of freedom
Residual deviance: 203.45  on 197  degrees of freedom
AIC: 385.51

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<section id="interpretando-los-resultados-de-un-glm-de-poisson" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="interpretando-los-resultados-de-un-glm-de-poisson"><span class="header-section-number">5.2.1</span> Interpretando los resultados de un GLM de Poisson</h3>
<p>La salida de resultados cuando ejecutamos la orden <code>summary()</code> en un GLM es muy parecida al de los modelos de regresión lineal, aunque con algunos matices. Por ejemplo, ahora no nos proporciona el R2 del modelo, ya que su cálculo no es posible. Además, si bien la significación de los coeficientes estimados tiene la misma interpretación que en modelos lineales (si p&lt; 0.05 podemos rechazar que esa variable no tenga un efecto), los valores de los coeficientes no pueden interpretarse de manera directa.</p>
<p>Por ejemplo, en el modelo ajustado más arriba vemos que, cuanto mayor es la nota en matemáticas, más premios han recibido, ya que el coeficiente de <code>math</code> es positivo y altamente significativo. Pero no podemos concluir que por cada punto que suba la nota de mates, se aumente en 0.086 el número de premios.</p>
<p>La manera de intepretar la salida es la siguiente: cuando <span class="math inline">\(x=0\)</span>, entonces el valor esperado es la media de <span class="math inline">\(y\)</span> y toma una valor de <span class="math inline">\(e^\alpha\)</span>, donde <span class="math inline">\(\alpha\)</span> es el intercepto. Con cada unidad de incremento en <span class="math inline">\(x\)</span>, el valor predicho tiene un efecto multiplicativo de <span class="math inline">\(e^\beta\)</span> en la media de <span class="math inline">\(y\)</span>, por lo tanto <span class="math inline">\(y=e^\alpha*e^{\beta*X}\)</span>, y si <span class="math inline">\(X = 0\)</span> entonces <span class="math inline">\(y = e^\alpha\)</span></p>
<p>En el ejemplo de arriba, el número medio de premios esperados es <span class="math inline">\(e^{-5.578057} = 0.00378\)</span>, y con cada punto de más que el alumno obtiene en mates, este número esperado de premios aumenta <span class="math inline">\(e^{0.086121} = 1.08\)</span> veces, es decir, aumenta un 8%.</p>
</section>
<section id="haciendo-predicciones-con-glms-de-poisson" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="haciendo-predicciones-con-glms-de-poisson"><span class="header-section-number">5.2.2</span> Haciendo predicciones con GLMs de Poisson</h3>
<p>Igual que hicimos con la regresión lineal, podemos obtener los valores predichos por el modelo, exactamente de la misma manera, con la función <code>predict()</code>. La única salvedad es que aquí tenemos que especificar el tipo de respuesta que queremos, con el argumento <code>type</code>. Esto es porque la función <code>predict()</code>, cuando el modelo es de tipo GLM, nos permite obtener el valor predicho para la variable respuesta (<code>type = "response"</code>) o el valor del predictor lineal que nos servía de enlace (<code>type = "link"</code>). En este caso - y casi siempre - nos interesa el primero, así que:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod.poisson, premios, <span class="at">type =</span> <span class="st">'response'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6         7         8 
0.1868820 0.1460475 0.2419764 0.2036898 0.1714611 0.1591828 0.2874596 0.1714611 
        9        10        11        12        13        14        15        16 
0.0938323 0.2874596 0.1714611 0.1275925 0.2419764 0.1324219 0.1714611 0.1229392 
       17        18        19        20        21        22        23        24 
0.1734994 0.1443317 0.2331516 0.1573126 0.1591828 0.2637393 0.1714611 0.1714611 
       25        26        27        28        29        30        31        32 
0.1962612 0.3290378 0.1891036 0.2246485 0.2541208 0.1652079 0.1591828 0.3133132 
       33        34        35        36        37        38        39        40 
0.1962612 0.3290378 0.1714611 0.1573126 0.3722052 0.1800664 0.1734994 0.1652079 
       41        42        43        44        45        46        47        48 
0.5793276 0.3586309 0.2139126 0.1573126 0.4260411 0.1868820 0.1573126 0.1229392 
       49        50        51        52        53        54        55        56 
0.4819345 0.3018867 0.2331516 0.1714611 0.2246485 0.3586309 0.1962612 0.1734994 
       57        58        59        60        61        62        63        64 
0.5061220 0.1591828 0.2637393 0.4474233 0.3133132 0.2331516 0.1962612 0.1714611 
       65        66        67        68        69        70        71        72 
0.4819345 0.4819345 0.2061113 0.3290378 0.4643584 0.4474233 0.3586309 0.3018867 
       73        74        75        76        77        78        79        80 
0.3908855 0.1460475 0.4421668 0.2246485 0.6240131 0.2246485 0.8175828 0.2331516 
       81        82        83        84        85        86        87        88 
0.5725215 0.5061220 0.3908855 0.2908769 0.6801357 0.4643584 0.2908769 0.5793276 
       89        90        91        92        93        94        95        96 
0.1591828 0.2874596 0.2637393 0.4876638 0.3133132 0.3586309 0.1868820 0.3766300 
       97        98        99       100       101       102       103       104 
0.6553312 0.5252789 0.4421668 0.5793276 0.3908855 0.1714611 0.4056806 0.7413059 
      105       106       107       108       109       110       111       112 
0.0871130 0.3290378 0.3170378 0.4876638 0.3018867 0.4260411 0.4643584 0.7785107 
      113       114       115       116       117       118       119       120 
1.4225834 0.6553312 0.5061220 0.7413059 0.5061220 0.5061220 0.5061220 0.3290378 
      121       122       123       124       125       126       127       128 
0.4421668 0.7142705 0.8485286 0.3908855 1.0986822 0.3586309 0.4643584 0.4643584 
      129       130       131       132       133       134       135       136 
0.5516417 0.6012554 0.3290378 0.9248437 0.2908769 0.6553312 1.4225834 0.5315234 
      137       138       139       140       141       142       143       144 
0.8485286 0.6553312 0.7785107 0.7142705 0.6553312 1.1974957 0.7501185 0.4474233 
      145       146       147       148       149       150       151       152 
0.9248437 0.6314313 0.5315234 0.7501185 0.5516417 0.6553312 1.0080225 0.6012554 
      153       154       155       156       157       158       159       160 
0.3908855 0.6801357 0.8175828 1.0986822 0.9248437 1.5505280 0.3018867 0.9248437 
      161       162       163       164       165       166       167       168 
0.5793276 0.2668747 1.3051964 1.0080225 0.9248437 0.5252789 0.6314313 1.1974957 
      169       170       171       172       173       174       175       176 
1.3051964 0.5315234 0.9712600 0.6553312 2.3850033 1.6092159 1.0080225 0.7142705 
      177       178       179       180       181       182       183       184 
1.0986822 1.1974957 2.3850033 1.1974957 1.8419734 2.0076372 1.4225834 0.6314313 
      185       186       187       188       189       190       191       192 
1.0080225 1.5505280 1.1974957 1.0986822 1.6899797 3.0881232 1.8419734 1.3051964 
      193       194       195       196       197       198       199       200 
2.1882005 2.1882005 0.8485286 2.1882005 3.4932624 2.1882005 2.3850033 2.5995063 </code></pre>
</div>
</div>
<p>Y como hicimos con la regresión lineal, podemos guardar estos datos como una columna en nuestro data frame <code>premios</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>premios<span class="sc">$</span>pred <span class="ot">&lt;-</span>  <span class="fu">predict</span>(mod.poisson, premios, <span class="at">type =</span> <span class="st">'response'</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(premios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id num_awards prog math      pred
1  45          0    3   41 0.1868820
2 108          0    1   41 0.1460475
3  15          0    3   44 0.2419764
4  67          0    3   42 0.2036898
5 153          0    3   40 0.1714611
6  51          0    1   42 0.1591828</code></pre>
</div>
</div>
<p>Y ahora podríamos generar una figura de valores predichos vs.&nbsp;observados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(num_awards <span class="sc">~</span> pred, <span class="at">data =</span> premios, <span class="at">pch =</span> <span class="dv">19</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02_GLM_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos que el ajuste no parece demasiado bueno. Esto nos indica que, si bien la nota de matemáticas es un buen predictor del número de premios obtenido, no parece que sea el único factor a tener en cuenta (lo cual es lógico).</p>
</section>
</section>
<section id="regresión-de-eventos-binomiales-regresión-logística" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="regresión-de-eventos-binomiales-regresión-logística"><span class="header-section-number">5.3</span> Regresión de eventos binomiales: regresión logística</h2>
<p>Vamos ahora a trabajar con la regresión logística, que es aquella que se usa cuando la variable respuesta es binomial, es decir, que sólo puede tomar valores 0 y 1. En este caso trabajaremos con el fichero <code>logit.csv</code> que incluye datos sobre incendios en España, y posibles factores causantes, entre 1988 y 2008. El fichero lo podéis encontrar en el campus virtual, y contiene las siguientes variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>datos_iiff <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"./data/glm/iiff_logit.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>logit_1_0</code>: la variable dependiente, codificada como 1 (fuego) y 0 (no fuego)</li>
<li><code>Cattle</code>: el número de cabezas de ganado ovino</li>
<li><code>Prot_area</code>: el area (en m^2) cubierta por figuras de protección</li>
<li><code>Powerlines</code>: área cubierta por líneas de alta tensión a menos de 200 m de zonas de bosque</li>
<li><code>Railroads</code>: area (en m^2) cubierta por líneas de ferrocarril a menos de 200 m de zonas boscosas</li>
<li><code>WAI</code>: Wildland-Agricultural interface es el área (en m^2) cubierta por la frontera entre bosques y cultivos.</li>
<li><code>WGI</code>: Wildland-Grassland interface es el área (en m^2) cubierta por la frontera entre bosques y pastos.</li>
<li><code>WUI</code>: Wildland-Urban Interface es el área (en m^2) cubierta por la frontera entre bosques y asentamientos urbanos</li>
<li><code>Machinery</code>: densidad de maquinaria agrícola</li>
<li><code>Tracks</code>: area cubierta por caminos a menos de 200 m de zonas boscosas.</li>
<li><code>Change_pop</code>: cambio relativo de población entre 1990 y 2010</li>
</ul>
<p>En principio, todos estos factores deberían tener un efecto positivo, es decir, cuanto mayor su valor, mayor probabilidad de ocurrencia de incendio - con la excepción probablemente de <code>Prot_area</code>.</p>
<p>Ajustemos por tanto el modelo de regresión. En realidad tenemos ya todo lo que necesitamos, excepto conocer la función de enlace a usar. En el caso de una regresión de este tipo, donde la variable respuesta es binomial, el argumento <code>family</code> debe tomar el valor <code>family = "binomial"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mod.logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(logit_1_0 <span class="sc">~</span> ., <span class="at">data =</span> datos_iiff, <span class="at">family =</span> binomial)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = logit_1_0 ~ ., family = binomial, data = datos_iiff)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.528e+00  9.995e-02 -15.290  &lt; 2e-16 ***
Cattle       1.114e-05  9.975e-06   1.117  0.26407    
Prot_area   -1.502e-07  1.335e-07  -1.125  0.26056    
Powerlines   2.070e-06  1.299e-06   1.593  0.11113    
Railroads    1.900e-06  5.890e-07   3.226  0.00125 ** 
WAI          1.466e-05  5.627e-07  26.060  &lt; 2e-16 ***
WGI         -1.567e-06  2.404e-07  -6.520 7.02e-11 ***
WUI          2.698e-06  1.058e-06   2.550  0.01078 *  
Machinery   -2.646e-02  1.796e-02  -1.474  0.14059    
FAPU         3.445e-07  1.887e-07   1.825  0.06794 .  
Tracks       8.281e-07  3.520e-07   2.353  0.01863 *  
Change_pop  -2.010e+00  3.959e-01  -5.077 3.84e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 4852.9  on 3581  degrees of freedom
Residual deviance: 2534.2  on 3570  degrees of freedom
AIC: 2558.2

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Vemos aquí qué variables efectivamente tienen un efecto significativo. ¿Es en todos los casos en el sentido esperado?</p>
<section id="interpretando-los-resultados-de-un-glm-logístico" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="interpretando-los-resultados-de-un-glm-logístico"><span class="header-section-number">5.3.1</span> Interpretando los resultados de un GLM logístico</h3>
<p>Igual que hemos comentado antes, los p-valores de las variables, así como el signo del coeficiente, tienen una interpretación directa. Sin embargo, el valor del coeficiente es más complejo de interpretar. En el caso de una regresón logística, la interpretación es similar a la regresión de Poisson. Cada aumento en una unidad de una variable <span class="math inline">\(x\)</span> multiplica la media predicha por <span class="math inline">\(e^\beta\)</span>, donde <span class="math inline">\(\beta\)</span> es el coeficiente de dicha variable explicativa. En el ejemplo de arriba, si aumenta el cambio de población en una unidad, el valor de probabilidad esperado se multiplicará por <span class="math inline">\(e^{-2.010} = 0.134\)</span>, es decir que la probabilidad de incendio disminuirá un <span class="math inline">\(1-0.134 = 0.86 = 86\%\)</span> respecto la media En el caso de los ferrocarriles, un aumento en la superficie de ferrocarril de 1m2 generará un cambio de <span class="math inline">\(e^{2.070e-06}= 1.000002076\)</span> en la probabilidad de incendio media. Como vemos, a pesar de que la variable es significativa, las magnitudes son pequeñas - lo cual es lógico si pensamos que la variable explicativa representa la superficie de ferrocarril en m2, no es esperable que un metro cuadrado de más aumente de manera brusca el riesgo de incendio.</p>
</section>
<section id="haciendo-predicciones-con-glm-logístico" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="haciendo-predicciones-con-glm-logístico"><span class="header-section-number">5.3.2</span> Haciendo predicciones con GLM logístico</h3>
<p>La manera de realizar las predicciones es la misma que hemos visto en el modelo de Poisson, con una salvedad:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mod.logit.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod.logit, datos_iiff, <span class="at">type =</span> <span class="st">'response'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Puesto que la variable respuesta era binomial, lo que cabría obtener son predicciones binarias, es decir, que sólo tomen valores de 0 o 1. Sin embargo, las predicciones son continuas. Esto es así porque lo que calcula es una <em>probabilidad</em> de que esa observación haya sufrido o no un incendio. Cuanto más cerca de uno, mayor es la probabilidad. Esta distribución se llama distribución <strong>logística</strong>, y por ello la regresión de eventos de salida binaria (si/no, hombre/mujer, etc.) a menudo se llama <strong>regresión logística.</strong> No obstante, si el modelo es bueno, la mayoría de los valores predichos deberían estar cerca de 0 o cerca de 1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mod.logit.pred, <span class="at">col=</span><span class="st">'steelblue'</span>,<span class="at">breaks =</span> <span class="dv">15</span>, <span class="at">xlab =</span> <span class="st">'Predicted probability'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02_GLM_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Guardemos las predicciones como una columna de nuestra tabla de datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>datos_iiff<span class="sc">$</span>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod.logit, datos_iiff, <span class="at">type =</span> <span class="st">'response'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora podríamos, por ejemplo, ver la distribución de valores predichos (que son continuos) respecto a los observados (que son binarios).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(predicted <span class="sc">~</span> logit_1_0, <span class="at">data =</span> datos_iiff, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"darkgreen"</span>, <span class="st">"darkred"</span>), <span class="at">xlab=</span> <span class="st">"Observados"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02_GLM_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos que en general, los casos donde no ha habido incendio (logit_1_0 = 0) tienen predicciones más bajas, lo que sugiere que el modelo ha funcionado bastante bien. Una opción de determinar el grado de acierto del modelo (ya que aquí no tenemos R^2) es calcular una <em>tabla de contingencia</em>, que es una tabla de aciertos y errores. Para ello debemos convertir nuestras predicciones en una variable binaria, definiendo un <em>umbral</em> o punto de corte, que por lógica podemos establecer en 0.5. De esta manera, todos los casos en los que la probabilidad predicha sea &gt; 0.5, los asignaremos a una predicción de que <strong>sí</strong> ha habido incendio, y al contrario:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>datos_iiff<span class="sc">$</span>pred_bin <span class="ot">=</span> <span class="fu">ifelse</span>(<span class="at">test =</span> datos_iiff<span class="sc">$</span>predicted <span class="sc">&gt;</span> <span class="fl">0.5</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">yes =</span> <span class="dv">1</span>, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">no =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora podemos construir una tabla de contingencia, usando la función <code>table()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">table</span>(datos_iiff<span class="sc">$</span>logit_1_0, datos_iiff<span class="sc">$</span>pred_bin)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(accuracy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
       0    1
  0 2044   64
  1  375 1099</code></pre>
</div>
</div>
<p>Y calcular el porcentaje de aciertos como la suma de la diagonal de esta tabla dividida entre el total de casos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>correctos <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(accuracy))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">sum</span>(accuracy)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>porc_correctos <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span>correctos<span class="sc">/</span>total</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>porc_correctos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 87.74428</code></pre>
</div>
</div>
<p>En este caso hemos obtenido un 88% de aciertos, es decir que el modelo clasifica bien el 88% de los eventos. Esta medida no se puede interpretar de la misma manera que un coeficiente de determinación (R<sup>2</sup>) pero sí nos da una idea de la bondad de nuestro modelo.</p>
</section>
</section>
<section id="conclusiones" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="conclusiones"><span class="header-section-number">5.4</span> Conclusiones</h2>
<p>Hemos visto como el ajuste de un modelo lineal generalizado en R no presenta mayor dificultad respecto a los modelos lineales. Sin embargo, hay que tener cuidado con la interpretación, que no es tan directa. Igualmente, cuando generemos predicciones debemos tener siempre en cuenta de indicar <code>type = "response"</code> para obtener los valores predichos para la variable dependiente. Aquí hemos visto cómo ajustar modelos de Poisson y logísticos, que son los más habituales, pero los GLMs incluyen otros como Gamma, Gaussiano, etc. Para saber más sobre GLMs y R os invito a consultar esta web: https://rpubs.com/JessicaP/459130</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01_RegresionLineal.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresión lineal en R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03_DatosEspaciales.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Trabajando con datos espaciales en R</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Apuntes y ejercicios de geoestadística para forestales. Aitor Ameztegui, Universitat de Lleida.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Este libro se ha elaborado con <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>