<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Apuntes y ejercicios de geoestadística para forestales - 9&nbsp; Interpolación espacial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07_RegresionEspacial.html" rel="next">
<link href="./05_PatronPuntos.html" rel="prev">
<link href="./images/udl.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03_DatosEspaciales.html">UNIDAD 2: GEOESTADÍSTICA Y ANÁLISIS ESPACIAL</a></li><li class="breadcrumb-item"><a href="./06_InterpolacionEspacial.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpolación espacial</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Apuntes y ejercicios de geoestadística para forestales</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ameztegui/labs_geoestadistica_forestal" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">UNIDAD 0: INTRODUCCION</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_Familiar_RStudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Familiarizándose con R y RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_Intro_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción a R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_RMarkdown_Quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introducción a Quarto y RMarkdown</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">UNIDAD 1: ANÁLISIS DE REGRESIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_RegresionLineal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresión lineal en R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regresión lineal generalizada (GLM) en R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">UNIDAD 2: GEOESTADÍSTICA Y ANÁLISIS ESPACIAL</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_DatosEspaciales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Trabajando con datos espaciales en R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_AutocorrelacionEspacial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Autocorrelación espacial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_PatronPuntos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Análisis de patrón de puntos en R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_InterpolacionEspacial.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpolación espacial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_RegresionEspacial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regresión espacial</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción-y-objetivo" id="toc-introducción-y-objetivo" class="nav-link active" data-scroll-target="#introducción-y-objetivo"><span class="header-section-number">9.1</span> Introducción y objetivo</a></li>
  <li><a href="#métodos-determinísticos-de-interpolación" id="toc-métodos-determinísticos-de-interpolación" class="nav-link" data-scroll-target="#métodos-determinísticos-de-interpolación"><span class="header-section-number">9.2</span> Métodos determinísticos de interpolación</a>
  <ul class="collapse">
  <li><a href="#método-de-polígonos-de-thiessen-o-voronoi-nearest-neighbor-interpolation" id="toc-método-de-polígonos-de-thiessen-o-voronoi-nearest-neighbor-interpolation" class="nav-link" data-scroll-target="#método-de-polígonos-de-thiessen-o-voronoi-nearest-neighbor-interpolation"><span class="header-section-number">9.2.1</span> Método de polígonos de Thiessen o Voronoi (nearest neighbor interpolation)</a></li>
  <li><a href="#inverse-distance-weighted-idw" id="toc-inverse-distance-weighted-idw" class="nav-link" data-scroll-target="#inverse-distance-weighted-idw"><span class="header-section-number">9.2.2</span> Inverse Distance Weighted (IDW)</a></li>
  </ul></li>
  <li><a href="#métodos-geoestadísticos-kriging" id="toc-métodos-geoestadísticos-kriging" class="nav-link" data-scroll-target="#métodos-geoestadísticos-kriging"><span class="header-section-number">9.3</span> Métodos geoestadísticos (kriging)</a>
  <ul class="collapse">
  <li><a href="#crear-el-semivariograma-observado" id="toc-crear-el-semivariograma-observado" class="nav-link" data-scroll-target="#crear-el-semivariograma-observado"><span class="header-section-number">9.3.1</span> Crear el semivariograma observado</a></li>
  <li><a href="#determinar-los-parámetros-del-semivariograma-teórico" id="toc-determinar-los-parámetros-del-semivariograma-teórico" class="nav-link" data-scroll-target="#determinar-los-parámetros-del-semivariograma-teórico"><span class="header-section-number">9.3.2</span> Determinar los parámetros del semivariograma teórico</a></li>
  <li><a href="#ajustar-el-semivariograma-teórico" id="toc-ajustar-el-semivariograma-teórico" class="nav-link" data-scroll-target="#ajustar-el-semivariograma-teórico"><span class="header-section-number">9.3.3</span> Ajustar el semivariograma teórico</a></li>
  <li><a href="#aplicar-el-modelo-de-kriging-a-los-datos" id="toc-aplicar-el-modelo-de-kriging-a-los-datos" class="nav-link" data-scroll-target="#aplicar-el-modelo-de-kriging-a-los-datos"><span class="header-section-number">9.3.4</span> Aplicar el modelo de kriging a los datos:</a></li>
  <li><a href="#otros-ajustes-de-kriging" id="toc-otros-ajustes-de-kriging" class="nav-link" data-scroll-target="#otros-ajustes-de-kriging"><span class="header-section-number">9.3.5</span> Otros ajustes de kriging</a></li>
  </ul></li>
  <li><a href="#validación-y-métricas-de-calidad-de-los-modelos-de-interpolación" id="toc-validación-y-métricas-de-calidad-de-los-modelos-de-interpolación" class="nav-link" data-scroll-target="#validación-y-métricas-de-calidad-de-los-modelos-de-interpolación"><span class="header-section-number">9.4</span> Validación y métricas de calidad de los modelos de interpolación</a>
  <ul class="collapse">
  <li><a href="#validación-cruzada" id="toc-validación-cruzada" class="nav-link" data-scroll-target="#validación-cruzada"><span class="header-section-number">9.4.1</span> Validación cruzada</a></li>
  <li><a href="#métricas-de-calidad" id="toc-métricas-de-calidad" class="nav-link" data-scroll-target="#métricas-de-calidad"><span class="header-section-number">9.4.2</span> Métricas de calidad</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">9.5</span> Conclusiones</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/ameztegui/labs_geoestadistica_forestal/edit/main/06_InterpolacionEspacial.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/ameztegui/labs_geoestadistica_forestal/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-Interpolation" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpolación espacial</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introducción-y-objetivo" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="introducción-y-objetivo"><span class="header-section-number">9.1</span> Introducción y objetivo</h2>
<p>Hasta ahora, hemos trabajado de varias maneras con el fichero de estaciones meteorólogicas del valle del Ebro (<code>estaciones.shp</code>). En primer lugar, extrajimos los valores de temperatura, así como una serie de predictores (elevación, distancia al Atlántico…) para ajustar modelos de regresión lineal. También utilizamos predictores continuos para generar mapas de temperatura espacialmente continuos, más allá de las zonas donde hay estaciones. Ahora haremos algo parecido, pero en vez de usar las variables explicativas (elevación, etc.) como predictores, vamos a utilizar los valores de temperatura medidos, así como su distribución espacial, para generar mapas continuos de temperatura. Es el proceso que se conoce como <strong>interpolación espacial</strong>, y veremos varios métodos. Pero antes de nada, debemos cargar las librerías y ficheros de datos necesarios. En este caso, además de los paquetes típicos que solemos usar (<code>tmap</code>, <code>sf</code>, <code>terra</code>…) usaremos la librería <code>gstat</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>estaciones <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">'data/meteo/meteo_espacial/estaciones_meteo.shp'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `estaciones_meteo' from data source 
  `C:\Users\Usuari\OneDrive - udl.cat\Teaching\EFCN_Geoestadística\Labs_Geoestadistica_Forestal\data\meteo\meteo_espacial\estaciones_meteo.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 90 features and 13 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 574966 ymin: 4514365 xmax: 818327 ymax: 4635648
Projected CRS: ETRS89 / UTM zone 30N</code></pre>
</div>
</div>
<p>Y podemos visualizar los datos, como hemos visto en otras unidades:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(estaciones) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_dots</span>(<span class="at">col=</span><span class="st">"Tmed_MES"</span>, <span class="at">size=</span><span class="fl">0.25</span>, <span class="at">title =</span> <span class="st">"Temp. media (ºC)"</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_text</span>(<span class="st">"Tmed_MES"</span>, <span class="at">just=</span><span class="st">"left"</span>, <span class="at">xmod=</span>.<span class="dv">5</span>, <span class="at">size =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_legend</span>(<span class="at">legend.outside=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Existen varios métodos de interpolación de información espacial, y se suelen clasificar en métodos <em>determinísticos</em> y métodos <em>geoestadísticos</em>. Los primeros simplemente realizan una inferencia de la información entre dos puntos “suavizando” la diferencia de valores entre ellos, mientras que los métodos geoestadísticos utilizan las propiedades estadísticas de los valores para realizar la interpolación. Veamos en primer lugar los métodos determinísticos:</p>
</section>
<section id="métodos-determinísticos-de-interpolación" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="métodos-determinísticos-de-interpolación"><span class="header-section-number">9.2</span> Métodos determinísticos de interpolación</h2>
<p>Exploraremos dos métodos determinísticos: <strong>vecino más próximo</strong> (aka <strong>Thiessen</strong>) y técnicas basadas en asignar pesos según el <strong>inverso de la distancia</strong> (<strong>IDW</strong>, de las siglas en inglés de <em>inverse distance weighted</em>).</p>
<section id="método-de-polígonos-de-thiessen-o-voronoi-nearest-neighbor-interpolation" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="método-de-polígonos-de-thiessen-o-voronoi-nearest-neighbor-interpolation"><span class="header-section-number">9.2.1</span> Método de polígonos de Thiessen o Voronoi (nearest neighbor interpolation)</h3>
<p>Es el método más simple (y más antiguo) de interpolación. Lo introdujo Alfred H. Thiessen hace más de un siglo. El procedimiento consiste en asignar, a cada punto del territorio no muestreado (para el que no tenemos información), el valor del punto muestreado más próximo. Esto genera una superficie <strong>teselada</strong> en el que las lineas que separan las teselas corresponden a la mitad de la distancia entre dos puntos. Estas líneas se conectan, de manera que cada área comprende uno de los puntos de la muestra.</p>
<p>Veamos como hacerlo en R, usando la función <code>voronoi()</code> de la librería <code>dismo</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dismo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: raster</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: sp</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>thiessen <span class="ot">&lt;-</span> <span class="fu">voronoi</span>(<span class="at">x =</span> <span class="fu">st_coordinates</span>(estaciones))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required namespace: deldir</code></pre>
</div>
</div>
<p>Veamos el objeto que ha generado esta función:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thiessen) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(estaciones, <span class="at">pch =</span> <span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<div id="note" style="background: #F5F5DC">
<p><strong>NOTA:</strong> ArcMap también ofrece la posibilidad de realizar una interpolación por polígonos de Thiessen, mediante la función <code>Natural neighbor</code> que se encuentra dentro del módulo <em>Spatial Analyst/Interpolation.</em></p>
</div>
</section>
<section id="inverse-distance-weighted-idw" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="inverse-distance-weighted-idw"><span class="header-section-number">9.2.2</span> Inverse Distance Weighted (IDW)</h3>
<p>El método IDW calcula un valor para cada punto sin él usando valores de los vecinos más próximos. Los pesos asignados a cada vecino son proporcionales a su cercanía al punto del que se quiere obtener el valor, y se pueden modular con el parámetro del exponente. Cuanto mayor sea dicho parámetro, más peso tendrán los puntos cercanos.</p>
<p>Para poder aplicar el idw, debemos, en primer lugar, crear un grid vacío a partir de un raster, al que después asignaremos los valores que determine la función. Para crear dicho grid y raster debemos seguir los siguientes pasos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos el raster vacío, con la misma extensión y crs que nuestros datos</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">ext</span>(estaciones), <span class="at">crs =</span> <span class="fu">crs</span>(estaciones))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos la resolución de este raster</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">res</span>(r) <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Lo convertimos a grid mediante la función `st_as_stars()` del paquete `stars`</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: abind</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">st_as_stars</span>(r, <span class="at">na.rm =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: [readValues] raster has no values</code></pre>
</div>
</div>
<p>Una vez generado el objeto <code>grid</code> podemos generar la interpolación, usando la función <code>idw()</code>, del paquete <code>gstat()</code>. Esta función tiene una notación parecida a la de la regresión, ya que debemos especificar una fórmula (en este caso <code>Tmed_MES ~ 1</code>), el dataset donde estan los datos (<code>estaciones</code>), y el objeto para el que queremos generar la interpolación (<code>grid</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>idw <span class="ot">&lt;-</span> <span class="fu">idw</span>(<span class="at">formula =</span> Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> estaciones, <span class="at">newdata =</span> grid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[inverse distance weighted interpolation]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
</div>
<p>Sin embargo, este objeto no tiene el formato <code>SpatRaster</code>, sino que es un objeto de tipo <code>stars</code> que contiene tanto la predicción como la varianza:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>idw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stars object with 2 dimensions and 2 attributes
attribute(s):
               Min. 1st Qu.   Median     Mean  3rd Qu.     Max.  NA's
var1.pred  15.81822 18.2985 19.97745 19.60785 20.73401 23.46503     0
var1.var         NA      NA       NA      NaN       NA       NA 29403
dimension(s):
  from  to  offset delta                refsys x/y
x    1 243  574966  1000 ETRS89 / UTM zone 30N [x]
y    1 121 4635365 -1000 ETRS89 / UTM zone 30N [y]</code></pre>
</div>
</div>
<p>En este caso, como el método es determinístico, el campo de la varianza sólo contiene valores de <code>NA</code> .</p>
<p><code>shj idw$var1.var}</code></p>
<p>Podemos plotear directamente este objeto de clase <code>stars</code> usando la función de siempre: <code>plot()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(idw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Sin embargo, si queremos convertirlo en un raster como los que hemos trabajado hasta ahora, tenemos que hacer una pequeña conversión. De esta manera, podremos usarlo en una función <code>tmap()</code> o añadirle puntos encima, etc.</p>
<p>Para la conversión podemos hacer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>idw_raster <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">as</span>(idw, <span class="st">"Raster"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora se ha convertido en un objeto <code>raster</code> normal, que contiene dos capas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>idw_raster</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
dimensions  : 121, 243, 2  (nrow, ncol, nlyr)
resolution  : 1000, 1000  (x, y)
extent      : 574966, 817966, 4514365, 4635365  (xmin, xmax, ymin, ymax)
coord. ref. : ETRS89 / UTM zone 30N (EPSG:25830) 
source(s)   : memory
names       : var1.pred, var1.var 
min values  :  15.81822,      NaN 
max values  :  23.46503,      NaN </code></pre>
</div>
</div>
<p>Y podemos visualizar los resultados de la interpolación como hemos hecho siempre con <code>plot()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(idw_raster<span class="sc">$</span>var1.pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Y añadir los puntos observados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(idw_raster<span class="sc">$</span>var1.pred)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(estaciones, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.8</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#text(estaciones, label= "Tmed_MES", cex = 0.8, pos = 2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Con esto ya habríamos completado la interpolación espacial usando el método IDW. Podríamos jugar con varios de los parámetros de la función: el número máximo de vecinos a considerar (<code>nmax</code>), o el exponente a usar en la fórmula (<code>idp</code>). Por ejemplo, si usamos un exponente alto:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>idw_15 <span class="ot">&lt;-</span> <span class="fu">idw</span>(<span class="at">formula =</span> Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> estaciones, <span class="at">newdata =</span> grid, <span class="at">idp =</span> <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[inverse distance weighted interpolation]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(idw_15)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Y si usamos uno muy bajo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>idw_0 <span class="ot">&lt;-</span> <span class="fu">idw</span>(<span class="at">formula =</span> Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> estaciones, <span class="at">newdata =</span> grid, <span class="at">idp =</span> <span class="fl">0.0001</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[inverse distance weighted interpolation]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(idw_0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Esto es todo lo que necesitamos saber sobre la interpolación mediante IDW. Este es uno de los métodos más usados, debido a que es simple y en la mayor parte de los casos funciona muy bien. Sin embargo, la elección del exponente no deja de ser subjetiva, y como acabamos de ver puede tener un efecto muy grande en las predicciones. Hay un segundo tipo de interpolaciones que usan la información espacial de los puntos (información de 1r y 2º orden) para derivar modelos probabilísticos con los valores predichos. Son los llamados métodos geoestadísticos.</p>
<div style="background: #F5F5DC">
<p><strong>NOTA:</strong> ArcGis y QGis también ofrecen la posibilidad de realizar una interpolación por IDW. En ArcGis Pro se puede hacer mediante la función <code>IDW</code> que se encuentra dentro del módulo <em>Spatial Analyst/Interpolation</em>. Esta función nos permite seleccionar el exponente de la ecuación, el radio de búsqueda de vecinos, definir obstáculos… En QGis se puede obtener mediante la herramienta <em>Spatial Analysis/Interpolation</em>.</p>
</div>
</section>
</section>
<section id="métodos-geoestadísticos-kriging" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="métodos-geoestadísticos-kriging"><span class="header-section-number">9.3</span> Métodos geoestadísticos (kriging)</h2>
<p>Tras aprender cómo interpolar siguiendo dos de los métodos determinísticos más típicos (polígonos de Thiessen e IDW), es el turno de los métodos geoestadísticos, entre los que el <em>kriging</em> es sin duda el más popular. Esta técnica se basa en modelos probabilísticos para calcular el valor de la variable respuesta en cualquier punto. El kriging se basa en el semivariograma de la variable que se quiere interpolar para ajustar y parametrizar un modelo, así que podríamos decir que funciona mejor cuanto mayor sea la autocorrelación espacial de la variable a interpolar. Es un método que además de generar las predicciones, ofrece también una estimación del error cometido en dichas estimación, lo que nos permite evaluar la calidad de la interpolación. Por último, permite un alto grado de personalización, de manera que con un ajuste adecuado de los parámetros se generan predicciones muy buenas.</p>
<p>El proceso es similar al que hemos visto en el ejemplo del IDW, Debemos generar un raster en “blanco” al que luego asignaremos los valores resultantes de la interpolación. La diferencia es que la interpolación por<em>kriging</em> se basa en el semivariograma, y por tanto, debemos generarlo. Los pasos a seguir serán por tanto:</p>
<ol type="1">
<li>Obtener el semivariograma empírico a partir de nuestros datos</li>
<li>Determinar los parámetros (rank, nugget, sill) del semivariograma teórico</li>
<li>Ajustar el semivariograma teórico</li>
<li>Ajustar el modelo de <em>kriging</em></li>
</ol>
<section id="crear-el-semivariograma-observado" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="crear-el-semivariograma-observado"><span class="header-section-number">9.3.1</span> Crear el semivariograma observado</h3>
<p>Podemos hacerlo directamente a partir de nuestro fichero de puntos, utilizando la función <code>variogram()</code>. Esta función ploteará el semivariograma a partir de los puntos observados, y podremos determinar los parámetros del semivariograma teórico (rank, nugget, sill). La sintaxis de la función <code>variogram()</code> es similar a la que hemos visto en IDW o en los modelos de regresión.</p>
<p>Mediante el argumento <code>formula</code> podemos definir el tipo de kriging a aplicar (los más típicos son <strong>ordinary kriging</strong> y <strong>universal kriging</strong>). En este ejemplo implementaremos un <strong>ordinary kriging</strong>, por lo que la fórmula será del tipo (<code>&lt;variable&gt; ~ 1</code>). No lo veremos aquí, pero en caso de querer interpilar usando el <em>universal kriging</em> la fórmula sería: <code>&lt;variable&gt; ~ x + y</code>.</p>
<p>Creemos por tanto el variograma empírico:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>ve <span class="ot">&lt;-</span> <span class="fu">variogram</span>(<span class="at">object =</span> Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> estaciones)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Y podemos visualizarlo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ve)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El argumento <code>width</code> controlará el tamaño de los bins que usemos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ve <span class="ot">&lt;-</span> <span class="fu">variogram</span>(<span class="at">object =</span> Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> estaciones,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="dv">5000</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ve)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="determinar-los-parámetros-del-semivariograma-teórico" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="determinar-los-parámetros-del-semivariograma-teórico"><span class="header-section-number">9.3.2</span> Determinar los parámetros del semivariograma teórico</h3>
<p>También podemos inspeccionar el objeto <code>ve</code> que acabamos de crear, para determinar los valores de <em>nugget</em>, <em>sill</em> y <em>rank</em> del semivariograma teórico que tendremos que ajustar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>ve</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    np      dist     gamma dir.hor dir.ver   id
1    8  3189.638 0.3714063       0       0 var1
2   30  8053.946 0.3220000       0       0 var1
3   43 12759.100 1.0726163       0       0 var1
4   57 17936.323 1.8665132       0       0 var1
5   85 22441.727 1.4648235       0       0 var1
6   81 27765.558 1.6893673       0       0 var1
7   98 32534.298 2.0248852       0       0 var1
8  109 37612.050 2.3637844       0       0 var1
9  117 42341.761 2.6563996       0       0 var1
10 127 47668.552 2.4657185       0       0 var1
11 136 52480.916 3.3991728       0       0 var1
12 132 57292.995 2.9894318       0       0 var1
13 139 62460.906 2.8742446       0       0 var1
14 146 67414.808 2.7391781       0       0 var1
15 145 72570.436 2.9318707       0       0 var1
16 124 77344.077 3.3316835       0       0 var1
17 157 82586.379 2.9459156       0       0 var1
18 151 87497.836 3.8211755       0       0 var1
19  19 90325.544 3.9195395       0       0 var1</code></pre>
</div>
</div>
<p>El <em>nugget</em> será el mínimo valor de <code>gamma</code> (en este caso, 0.3943), el <em>sill</em> se alcanza cuando <em>gamma</em> se estabiliza (3.3992), y el <em>range</em> será la distancia a la que se alcanza el <em>sill</em> (52480.916). Estos números los emplearemos en el siguiente paso, cuando ajustemos el semivariograma teórico.</p>
</section>
<section id="ajustar-el-semivariograma-teórico" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="ajustar-el-semivariograma-teórico"><span class="header-section-number">9.3.3</span> Ajustar el semivariograma teórico</h3>
<p>Para este paso debemos modelizar una curva que ajuste lo mejor posible los valores del semivariograma empírico. Para ello, debemos seleccionar la forma que queremos que tenga el semivariograma, y asignarle los parámetros que hemos definido antes. Podemos acceder al catálogo de formas disponibles mediante:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show.vgms</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En este caso vamos a seleccionar la curva de tipo “Exp”, y la aplicaremos con la función <code>fit.variogram()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(ve, <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="fl">3.3992</span>, <span class="at">model =</span> <span class="st">"Exp"</span>, <span class="at">range =</span> <span class="fl">52480.916</span>, <span class="at">nugget =</span> <span class="fl">0.3943</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>vt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  model    psill    range
1   Nug 0.000000     0.00
2   Exp 3.957497 43325.59</code></pre>
</div>
</div>
<p>Ahora podemos plotearlo, a ver si realmente ajusta bien:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ve, <span class="at">pl =</span> T, <span class="at">model =</span> vt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos que, efectivamente, el ajuste es bastante bueno, por lo que nos conformamos con el semivariograma teórico ajustado.</p>
</section>
<section id="aplicar-el-modelo-de-kriging-a-los-datos" class="level3" data-number="9.3.4">
<h3 data-number="9.3.4" class="anchored" data-anchor-id="aplicar-el-modelo-de-kriging-a-los-datos"><span class="header-section-number">9.3.4</span> Aplicar el modelo de kriging a los datos:</h3>
<p>A partir de aquí el procedimiento es similar al que hemos visto para <em>IDW</em>: debemos crear un raster vacío con la extensión del área a analizar, y después le asignaremos los valores generados por el kriging. Como antes ya hemos generado el objeto <code>grd</code>, no necesitamos volver a hacerlo, y podemos generar la interpolación, de forma similar a la que hemos visto antes, usando la función <code>krige()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">krige</span>(Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> estaciones, <span class="at">newdata =</span> grid, <span class="at">model =</span> vt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[using ordinary kriging]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>k</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stars object with 2 dimensions and 2 attributes
attribute(s):
                   Min.    1st Qu.     Median       Mean   3rd Qu.      Max.
var1.pred  15.838643541 17.9220405 20.1211162 19.5900002 21.061067 23.420031
var1.var    0.003102869  0.6709149  0.9144648  0.9501347  1.213168  2.680639
dimension(s):
  from  to  offset delta                refsys x/y
x    1 243  574966  1000 ETRS89 / UTM zone 30N [x]
y    1 121 4635365 -1000 ETRS89 / UTM zone 30N [y]</code></pre>
</div>
</div>
<p>El objeto generado (<code>k</code>) contiene, igual que antes, 2 dimensiones: las predicciones (columna <code>var1.pred</code>), y la varianza (precisión) de las predicciones (columna <code>var1.var</code>), que en este caso sí contiene valores. Podemos plotear los resultados, y por defecto nos mostrará el valor de la predicción:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Si queremos especificar la varianza, también lo podemos hacer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k[<span class="st">"var1.var"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos que la varianza es mínima - de hecho 0 - en los puntos, y se hace mayor en las zonas sin densidad de puntos.</p>
<p>Igual que antes, podemos transformar este objeto a uno de tipo <code>SpatRaster</code> para hacerlo más integrable con otro tipo de visualizaciones:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>k2 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">as</span>(k, <span class="st">"Raster"</span>))</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>k2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
dimensions  : 121, 243, 2  (nrow, ncol, nlyr)
resolution  : 1000, 1000  (x, y)
extent      : 574966, 817966, 4514365, 4635365  (xmin, xmax, ymin, ymax)
coord. ref. : ETRS89 / UTM zone 30N (EPSG:25830) 
source(s)   : memory
names       : var1.pred,    var1.var 
min values  :  15.83864, 0.003102869 
max values  :  23.42003, 2.680639443 </code></pre>
</div>
</div>
<p>Veamos el aspecto de la interpolación generada:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k2<span class="sc">$</span>var1.pred, <span class="at">main =</span> <span class="st">"Predicción"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Incluso podemos representar encima los puntos observados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k2<span class="sc">$</span>var1.pred, <span class="at">main =</span> <span class="st">"Predicció"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(estaciones, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.8</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Echemos ahora un vistazo a la precisión de las predicciones:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k2<span class="sc">$</span>var1.var, <span class="at">main =</span> <span class="st">"Varianza"</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(estaciones, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.8</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos, como comentábamos antes, que el error es mínimo en cada una de las observaciones, y mayor en las zonas donde hay espacios grandes sin datos de estaciones.</p>
<p>Existe una función que automatiza todo el proceso de ajuste del modelo de kriging, de manera que no hay que determinar los parámetros, la forma, etc. manualmente. Si estáis pensando que podía haber explicado este método desde el principio, tened en cuenta que es importante entender cómo se genera el proceso antes de realizarlo de manera automática. La función en cuestión es <code>autoKrige()</code>, del paquete <code>automap</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(automap)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>autok <span class="ot">&lt;-</span> <span class="fu">autoKrige</span>(Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, estaciones,  grid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[using ordinary kriging]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>autok<span class="sc">$</span>var_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  model     psill    range kappa
1   Nug 0.1569758     0.00   0.0
2   Ste 3.6365982 52150.83   0.7</code></pre>
</div>
</div>
<p>Además, nos genera un output muy adecuado con sólo usar la función <code>plot()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(autok)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div style="background: #F5F5DC">
<p><strong>NOTA</strong>: ArcGIS y QGis también ofrece la posibilidad de realizar una interpolación por kriging, mediante la función <code>Kriging</code> que se encuentra dentro del módulo <em>Spatial Analyst/Interpolation</em> o <em>Spatial Analysis/Interpolation</em></p>
</div>
<p>Esto es todo lo que necesitamos saber de la interpolación mediante kriging. El hecho de que permita optimizar los parámetros y que nos proporciones estimaciones de la precisión hacen sin duda del <em>kriging</em> el método de interpolación más completo y utilizado.</p>
</section>
<section id="otros-ajustes-de-kriging" class="level3" data-number="9.3.5">
<h3 data-number="9.3.5" class="anchored" data-anchor-id="otros-ajustes-de-kriging"><span class="header-section-number">9.3.5</span> Otros ajustes de kriging</h3>
<p>El modelo de kriging que hemos usado hasta ahora es un kriging ordinario, lo que se indica al ajustar la función <code>krige()</code>, indicando <code>Tmed_MES ~ 1</code>. Para seleccionar otro tipo de kriging, podemos cambiar la notación de esa fórmula, de acuerdo a lo siguiente:</p>
<ul>
<li>Kriging simple: <code>Z ~ 1</code> (requiere definir el parámetro <code>beta</code> )</li>
<li>Kriging ordinario: <code>Z ~ 1</code></li>
<li>Kriging universal: <code>Z ~ x + y</code></li>
</ul>
<p>Veamos por ejemplo cual sería el resultado de un ajuste por kriging universal, el método más común:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>estaciones<span class="sc">$</span>x <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(estaciones)[,<span class="dv">1</span>]</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>estaciones<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(estaciones)[,<span class="dv">2</span>]</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>uk <span class="ot">&lt;-</span> <span class="fu">krige</span>(Tmed_MES<span class="sc">~</span> x <span class="sc">+</span> y, <span class="at">locations =</span> estaciones, <span class="at">newdata =</span> grid, <span class="at">model =</span> vt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[using universal kriging]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>uk2 <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">as</span>(uk, <span class="st">"Raster"</span>))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(uk2<span class="sc">$</span>var1.pred, <span class="at">main =</span> <span class="st">"Predicción por Universal kriging"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>auto_uk <span class="ot">&lt;-</span> <span class="fu">autoKrige</span>(Tmed_MES <span class="sc">~</span> x <span class="sc">+</span> y, estaciones,  grid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[using universal kriging]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): complete map seems to be NA's -- no selection was
made</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(auto_uk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-31-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="validación-y-métricas-de-calidad-de-los-modelos-de-interpolación" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="validación-y-métricas-de-calidad-de-los-modelos-de-interpolación"><span class="header-section-number">9.4</span> Validación y métricas de calidad de los modelos de interpolación</h2>
<p>Tras haber interpolado en base a dos métodos (IDW y kriging) se hace necesario evaluar cómo de buenas son esas interpolaciones. Esto lo haremos mediante una validación cruzada y el cálculo de una serie de métricas de calidad del modelo:</p>
<section id="validación-cruzada" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="validación-cruzada"><span class="header-section-number">9.4.1</span> Validación cruzada</h3>
<p>La validación cruzada consiste en comparar, para cada valor de la muestra (cada observación) la diferencia entre el valor observado y el predicho por el modelo. Sin embargo, no podemos incluir el punto u observación que queremos evaluar, ya que si no la predicción sería exactamente igual a la observación. Por ello, lo que se hace es ir excluyendo una a una las observaciones, y se determina cuál sería el valor predicho para ese punto por un modelo elaborado con todos los demás puntos. Esto se hace de manera repetitiva - iterativa - con todos los puntos de la muestra, y al final tendremos una serie de valores (residuos) de la diferencia entre el valor observado y el predicho.</p>
<p><code>R</code> nos pone fácil realizar la validación cruzada, a través de la función <code>krige.cv()</code>, del paquete <code>gstat</code>. Dicha función permite como entrada un objeto de tipo <code>gstat</code> en el argumento <code>model</code>, que es lo que determinará el tipo de interpolación que hacemos. Así, si no indicamos nada en <code>model</code>, realizará una interpolación por IDW:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>idw_cv <span class="ot">&lt;-</span> <span class="fu">krige.cv</span>(<span class="at">formula =</span> Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> estaciones) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Vemos que tarda más que antes, ya que tiene que hacer numerosas interpolaciones. Una vez ajustado, podemos acceder a los datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>idw_cv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 90 features and 6 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 574966 ymin: 4514365 xmax: 818327 ymax: 4635648
Projected CRS: ETRS89 / UTM zone 30N
First 10 features:
   var1.pred var1.var observed   residual zscore fold               geometry
1   18.19902       NA    15.80 -2.3990215     NA    1 POINT (666121 4514365)
2   20.96552       NA    22.45  1.4844775     NA    2 POINT (814489 4514857)
3   17.22110       NA    15.85 -1.3711008     NA    3 POINT (620767 4515276)
4   18.80757       NA    16.70 -2.1075670     NA    4 POINT (705449 4516865)
5   17.51609       NA    17.25 -0.2660859     NA    5 POINT (681326 4520030)
6   17.61897       NA    16.10 -1.5189729     NA    6 POINT (593975 4522166)
7   19.69973       NA    18.80 -0.8997303     NA    7 POINT (758868 4522277)
8   17.78630       NA    17.00 -0.7862966     NA    8 POINT (686217 4522281)
9   20.50400       NA    23.20  2.6960017     NA    9 POINT (794466 4524785)
10  16.83975       NA    16.30 -0.5397491     NA   10 POINT (620133 4526863)</code></pre>
</div>
</div>
<p>Vemos que contiene los valor predichos, los observados, y el residuo. Esto nos permite representar el gráfico de valores observados y predichos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(idw_cv<span class="sc">$</span>observed, idw_cv<span class="sc">$</span>var1.pred) <span class="sc">+</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>Esto mismo lo podemos hacer para el modelo de interpolado mediante ordinary kriging, simplemente indicando el modelo de variograma que queremos (<code>model = vt</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>ok_cv <span class="ot">&lt;-</span> <span class="fu">krige.cv</span>(<span class="at">formula =</span> Tmed_MES <span class="sc">~</span> <span class="dv">1</span>, <span class="at">locations =</span> estaciones,  <span class="at">model =</span> vt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ok_cv<span class="sc">$</span>observed, ok_cv<span class="sc">$</span>var1.pred, </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Observed vs. predicted for Ordinary kriging"</span>) <span class="sc">+</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>… o el de universal kriging, donde además de <code>model</code> debemos especificar la fórmula correspondiente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>uk_cv <span class="ot">&lt;-</span> <span class="fu">krige.cv</span>(Tmed_MES<span class="sc">~</span>x<span class="sc">+</span>y, <span class="at">locations =</span> estaciones,  <span class="at">model =</span> vt)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(uk_cv<span class="sc">$</span>observed, uk_cv<span class="sc">$</span>var1.pred, </span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Observed vs. predicted for Universal kriging"</span>) <span class="sc">+</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
</section>
<section id="métricas-de-calidad" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="métricas-de-calidad"><span class="header-section-number">9.4.2</span> Métricas de calidad</h3>
<p>La validación cruzada ya es una pista muy buena de si la interpolación que hemos generado es adecuada o no, ya que nos permite evaluar los sesgos en las predicciones - una predicción no sesgada debería ajustarse de manera simétrica y cercana a la recta 1:1 entre valores observados y predichos-. Pero hay maneras más cuantitativas de realizar una evaluación de la calidad del modelo. Para ello podemos calcular algunos indicadores o métricas:</p>
<ul>
<li><strong>Correlación observados-predichos</strong></li>
</ul>
<p>Lógicamente, cuanto mayor sea la correlación entre valores observados y predichos, mejor será el modelo ajustado. Podemos calcularlo para el IDW y el kriging:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># IDW</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(idw_cv<span class="sc">$</span>var1.pred, idw_cv<span class="sc">$</span>observed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8598952</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordinary Krigging</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(ok_cv<span class="sc">$</span>var1.pred, ok_cv<span class="sc">$</span>observed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8713259</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Universal Krigging</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(uk_cv<span class="sc">$</span>var1.pred, uk_cv<span class="sc">$</span>observed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8774583</code></pre>
</div>
</div>
<p>Vemos que en todos los casos son muy altos, y son valores muy similares.</p>
<ul>
<li><strong>Media de los residuos (error medio, ME)</strong></li>
</ul>
<p>Tal y como vimos en la unidad relativa a la regresión lineal, nos interesa aquí que los residuos sean lo más pequeños posible (en valor absoluto) y que además tengan media próxima a cero. Podemos calcular la media:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#IDW</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(idw_cv<span class="sc">$</span>residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.07808131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordinary Kriging</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(ok_cv<span class="sc">$</span>residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.02155456</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Universal Kriging</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(uk_cv<span class="sc">$</span>residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.02068641</code></pre>
</div>
</div>
<p>…y además construir el boxplot o histograma</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(idw_cv<span class="sc">$</span>residual, <span class="at">main =</span> <span class="st">"Histograma de residuos para IDW"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ok_cv<span class="sc">$</span>residual,  <span class="at">main =</span> <span class="st">"Histograma de residuos para ordinary kriging"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-40-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(uk_cv<span class="sc">$</span>residual,  <span class="at">main =</span> <span class="st">"Histograma de residuos para universal kriging"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_InterpolacionEspacial_files/figure-html/unnamed-chunk-40-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos también que parecen normales y centrados en el cero.</p>
<ul>
<li><strong>Media estandarizada del error de predicción (mean square predictor error; MSPE)</strong></li>
</ul>
<p>El MSPE es la media del cuadrado de los errores de predicción, es decir, de los residuos. Interesa por tanto que sea lo más pequeño posible:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para IDW</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(idw_cv<span class="sc">$</span>residual<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.254002</code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para ordinary Kriging</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(ok_cv<span class="sc">$</span>residual<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.030617</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para universal Kriging</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(uk_cv<span class="sc">$</span>residual<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9851296</code></pre>
</div>
</div>
<ul>
<li><strong>Raíz del error cuadrático medio (Root of Mean Squared Error; RMSE)</strong>:</li>
</ul>
<p>El RMSE es una medida muy común de <em>performance</em> de un modelo. Es la raíz del cociente entre la suma de los cuadrados de los residuos y el número de observaciones. Tiene la ventaja de que está en las mismas unidades que la variable respuesta, por lo que su valor es fácilmente interpretable como una especie de “error medio” en las predicciones:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para IDW</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>(idw_cv<span class="sc">$</span>residual<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">length</span>(idw_cv<span class="sc">$</span>residual))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.119822</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para ordinary kriging</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>(ok_cv<span class="sc">$</span>residual<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">length</span>(ok_cv<span class="sc">$</span>residual))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.015193</code></pre>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para universal kriging</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>(uk_cv<span class="sc">$</span>residual<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">length</span>(uk_cv<span class="sc">$</span>residual))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.992537</code></pre>
</div>
</div>
<p>Podemos incluso hacer una tabla resumen con los parámetros:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Metodo</th>
<th style="text-align: right;">Correlacion</th>
<th style="text-align: right;">ME</th>
<th style="text-align: right;">MSPE</th>
<th style="text-align: right;">MRSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IDW</td>
<td style="text-align: right;">0.8598952</td>
<td style="text-align: right;">-0.0780813</td>
<td style="text-align: right;">1.2540020</td>
<td style="text-align: right;">1.119822</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ordinary kriging</td>
<td style="text-align: right;">0.8713259</td>
<td style="text-align: right;">-0.0215546</td>
<td style="text-align: right;">1.0306172</td>
<td style="text-align: right;">1.015193</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Universal kriging</td>
<td style="text-align: right;">0.8774583</td>
<td style="text-align: right;">-0.0206864</td>
<td style="text-align: right;">0.9851296</td>
<td style="text-align: right;">0.992537</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En este caso, todos los indicadores parecen favorecer el kriging: los residuos son más bajos, las métricas de error también, y la correlación entre valores observados y predichos es ligeramente mejor. Por tanto, consideraremos que esta interpolación es más adecuada que la de IDW. En concreto, el <em>universal kriging</em> parece ser el método que produce las mejores predicciones (aunque por poco, los tres métodos son bastante similares).</p>
</section>
</section>
<section id="conclusiones" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="conclusiones"><span class="header-section-number">9.5</span> Conclusiones</h2>
<p>Con esto hemos visto cómo producir interpolaciones con diversas métricas, y cómo evaluar la calidad de la interpolación generada. El kriging acostumbra a ser el método más robusto, pero también es computacionalmente más exigente. La decisión final dependerá del objetivo, la precisión requerida, y la disponibilidad de tiempo y de capacidad de computación. En <a href="https://r-lidar.github.io/lidRbook/dtm.html#sec-dtm-pros-cons">este enlace</a> podéis ver una discusión sobre los pros y contras de cada método usando como ejemplo el procesado de ficheros LiDAR para generar un MDT (es materia que se cubre en la asignatura “Tecnologies Digitals 2: Arbre i rodal” del Màster en Enginyeria de Forests). En el ejemplo con el que hemos trabajado, sin embargo, un IDW muestra ser suficientemente preciso.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05_PatronPuntos.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Análisis de patrón de puntos en R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07_RegresionEspacial.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regresión espacial</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Apuntes y ejercicios de geoestadística forestal. Aitor Ameztegui, Universitat de Lleida.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Este libro se ha elaborado con <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>